### ISSUE TITLE
[Test Kitchen] Default CENT-OS image not going to the official centos image

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1311]
## Description
Until recently users in kitchen could use the official centos images in kitchen without any additional image search parameters. This has changed now as if you stay in the defaults you get an image from a company called Supported Images as opposed to the official Centos image.  Link included.

```
https://aws.amazon.com/marketplace/pp/B07X8R39Q3/#pdp-support
```

To Reproduce:
```
platforms:
  - name: centos-7
```

this to make it work as intended:

```
platforms:
  - name: centos-7
    driver:
      image_search:
        product-code: aw0evgkw8e5c1q413zgy5pjce
        owner-alias: aws-marketplace
        name:
          - CentOS Linux 7*
          - CentOS-7*-GA-*
```

## Chef Workstation Version
20.6

## Acceptance criteria

The default image returned when using a `centos-*` name is the official image owned by Centos

Fixes https://github.com/test-kitchen/kitchen-ec2/issues/456
Fixes customer-bugs 136
