### ISSUE TITLE
Chef install Failed to generate Policyfile.lock: kitchen test suite policyfile

### ISSUE THREAD

**Issue by taqtiqa-mark** [chef/chef-workstation#1602]
# Description

Running
```
kitchen test global-ubuntu-1804
```
Fails to build Policyfile.lock.

# ChefDK Version

```
$ chef --version
Chef Development Kit Version: 3.11.3
chef-client version: 14.13.11
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.25.0
inspec version: 3.9.3
```
# Platform Version

Ubuntu 18.04
ChefDK 3.11.3

# Replication Case

`.kitchen.yml` contains:

```
---
driver:
  name: dokken
  privileged: true
  env: [CHEF_LICENSE=accept]

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  -
    name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install sudo -y

suites:
  - name: global
    provisioner:
      policyfile: test/fixtures/cookbooks/test/policyfiles/global.rb
    verifier:
      inspec_tests:
        - test/integration/global
    attributes:
```

`test/fixtures/cookbooks/test/policyfiles/global.rb` contains:
```
name 'Test Global Recipe'

path = File.expand_path('base.rb', __dir__)
instance_eval(IO.read(path))

#include_policy 'base', path: '.'
# The run list is also ignored by ChefSpec but you need to specify one.
run_list 'test::global'
```

`test/fixtures/cookbooks/test/policyfiles/base.rb` contains:
```
cookbook 'test', path: '.'
cookbook 'jlenv', path: '../../../../'
```

# Stacktrace

```
$ chef install /home/<user>/src/jlenv-cookbook/test/fixtures/cookbooks/test/policyfiles/global.rb
Building policy Test Global Recipe
Expanded run list: recipe[test::global]
Caching Cookbooks...
Installing test  >= 0.0.0 from path
Error: Failed to generate Policyfile.lock
Reason: (CookbookOmnifetch::NotACookbook) The resource at '/home/<user>/src/jlenv-cookbook/test/fixtures/cookbooks/test/policyfiles' does not appear to be a valid cookbook. Does it have a metadata.rb?
```
