### ISSUE TITLE
Kitchen Google driver version bump to 2.4.0

### ISSUE THREAD

**Issue by estedev** [chef/chef-workstation#3144]
### Describe the Enhancement:
The current Kitchen Google driver version in Chef Workstation is 2.3.0. This request is to get it bumped up to 2.4.0.

### Describe the Need:
The 2.4.0 version of the Kitchen Google driver adds support for accelerator(s), eg. GPU.
```
driver:
  name: gce
  ...
  machine_type: n1-standard-4
  guest_accelerators:
    - type: nvidia-tesla-t4
       count: 2
```

### Current Alternative
Manually bumping the kitchen-google gem would be the current alternative.

### Can We Help You Implement This?:
I'm happy to update the Gemfile.lock myself in a PR if that is the desired approach/helpful at all (not sure whether there's a monthly bump that happens anyway by the maintainers)...

Thanks in advance for your feedback!
